version: "2"
services:
  web:
    build: .
    command: java -jar target/Spring-Data-Rest-Seed-0.1.0.jar
    ports:
      - '${APP_PORT}:8080'
    volumes:
      - .:/code
      - ./dependencies:/root/.m2
